### PR TITLE
Big-endian friendly uint16_t handling

### PR DESCRIPTION
**Pull request by dstebila**

### CODE REVIEW

**Comment by dstebila** [comment]
Tested successfully on PowerPC via PQClean (https://github.com/PQClean/PQClean/runs/89571287)

**Comment by dstebila** [comment]
AES matrix generation also big-endian safe now. Should be ready for review and merge, @patricklonga.  I've run a selection of consistency tests but not every combination that your run-all script does.

**Comment by patricklonga** [comment]
In config.h, is __BYTE_ORDER__ expected to be defined by the OS? 
Also, is _WIN32 expected to be set when either our macros _X86_ or _AMD64_ are set? if this is the case maybe use these two macros instead.

**Comment by dstebila** [comment]
> In config.h, is **BYTE_ORDER** expected to be defined by the OS?

`__BYTE_ORDER__` is a [GCC C preprocessor macro](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html). It's not POSIX, so not all compilers define it (including Microsoft's compiler) which is why there's fall-through code when it's not defined.

> Also, is `_WIN32` expected to be set when either `_X86_` or `_AMD64_` are set? if this is the case maybe use these two macros instead.

Yes.  But macros for specific CPU architectures are annoyingly non-standardized across compilers, see https://sourceforge.net/p/predef/wiki/Architectures/.  I used `_WIN32` to avoid that, but your choice if you prefer more specific macros.

**Comment by patricklonga** [comment]
Still in config.h. Is it necessary to check if `__BYTE_ORDER__` is defined? apparently this is covered by the evaluations `__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__` and `__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__`. But I could be wrong.

**Comment by dstebila** [comment]
> Still in config.h. Is it necessary to check if `__BYTE_ORDER__` is defined? apparently this is implicitly covered by the evaluations `__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__` and `__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__`. But I could be wrong.

I think it is necessary to still check if `__BYTE_ORDER__` is defined.  As far as I can tell, equality of two undefined macros is true.  At least, the following program prints "if" on both clang and gcc for me:

```c
#include <stdio.h>

int main() {
#if POTATO == FRENCH_FRIES
    printf("if\n");
#else
    printf("else\n");
#endif
}
```

**Comment by patricklonga** [comment]
It goes against intuition but yes, I just tried it too and we need those definition checks.

**Pull request merged**
